'use strict';

/**
 * hsk2-vocab.js
 * HSK 2 vocabulary — the ~150 new words introduced at HSK 2.
 * (Does not repeat the 150 HSK 1 words already in hsk1-vocab.js)
 */
const HSK2_VOCAB = [
  // ── Pronouns / Determiners
  { word: "大家",  pinyin: "dàjiā",     english: "everyone / everybody",     type: "pron" },

  // ── Numbers / Quantity
  { word: "两",    pinyin: "liǎng",     english: "two (before measure words)", type: "num" },
  { word: "一共",  pinyin: "yīgòng",    english: "altogether / in total",    type: "adv" },
  { word: "一般",  pinyin: "yībān",     english: "generally / usually",      type: "adv" },
  { word: "一定",  pinyin: "yīdìng",    english: "definitely / certainly",   type: "adv" },
  { word: "一起",  pinyin: "yīqǐ",      english: "together",                 type: "adv" },
  { word: "一直",  pinyin: "yīzhí",     english: "straight / all along",     type: "adv" },

  // ── Measure Words
  { word: "次",    pinyin: "cì",        english: "time / occurrence",        type: "mw" },
  { word: "位",    pinyin: "wèi",       english: "(polite MW for people)",   type: "mw" },
  { word: "双",    pinyin: "shuāng",    english: "pair (shoes, chopsticks)", type: "mw" },
  { word: "条",    pinyin: "tiáo",      english: "strip-shaped things",      type: "mw" },
  { word: "张",    pinyin: "zhāng",     english: "flat things (paper, table)", type: "mw" },
  { word: "件",    pinyin: "jiàn",      english: "item (clothes, matters)",  type: "mw" },
  { word: "道",    pinyin: "dào",       english: "dish / road / course",     type: "mw" },
  { word: "匹",    pinyin: "pǐ",        english: "(MW for horses)",          type: "mw" },

  // ── People
  { word: "哥哥",  pinyin: "gēgē",      english: "older brother",            type: "noun" },
  { word: "姐姐",  pinyin: "jiějie",    english: "older sister",             type: "noun" },
  { word: "弟弟",  pinyin: "dìdi",      english: "younger brother",          type: "noun" },
  { word: "妹妹",  pinyin: "mèimei",    english: "younger sister",           type: "noun" },
  { word: "奶奶",  pinyin: "nǎinai",    english: "paternal grandmother",     type: "noun" },
  { word: "爷爷",  pinyin: "yéyé",      english: "paternal grandfather",     type: "noun" },
  { word: "叔叔",  pinyin: "shūshu",    english: "uncle (father's brother)", type: "noun" },
  { word: "妻子",  pinyin: "qīzi",      english: "wife",                     type: "noun" },
  { word: "丈夫",  pinyin: "zhàngfu",   english: "husband",                  type: "noun" },
  { word: "孩子",  pinyin: "háizi",     english: "child / children",         type: "noun" },
  { word: "先生",  pinyin: "xiānsheng", english: "Mr. / sir / husband",      type: "noun" },
  { word: "同事",  pinyin: "tóngshì",   english: "colleague",                type: "noun" },
  { word: "服务员", pinyin: "fúwùyuán", english: "waiter / attendant",       type: "noun" },

  // ── Place
  { word: "宾馆",  pinyin: "bīnguǎn",   english: "hotel",                    type: "noun" },
  { word: "机场",  pinyin: "jīchǎng",   english: "airport",                  type: "noun" },
  { word: "地铁",  pinyin: "dìtiě",     english: "subway / metro",           type: "noun" },
  { word: "银行",  pinyin: "yínháng",   english: "bank",                     type: "noun" },
  { word: "公园",  pinyin: "gōngyuán",  english: "park",                     type: "noun" },
  { word: "教室",  pinyin: "jiàoshì",   english: "classroom",                type: "noun" },
  { word: "路",    pinyin: "lù",        english: "road / route",             type: "noun" },
  { word: "门",    pinyin: "mén",       english: "door / gate",              type: "noun" },
  { word: "外",    pinyin: "wài",       english: "outside",                  type: "noun" },
  { word: "旁边",  pinyin: "pángbiān",  english: "beside / next to",         type: "noun" },
  { word: "左边",  pinyin: "zuǒbiān",   english: "left side",                type: "noun" },
  { word: "右边",  pinyin: "yòubiān",   english: "right side",               type: "noun" },
  { word: "楼",    pinyin: "lóu",       english: "floor / building / storey", type: "noun" },

  // ── Time
  { word: "早上",  pinyin: "zǎoshang",  english: "morning (early)",          type: "noun" },
  { word: "上午",  pinyin: "shàngwǔ",   english: "morning (AM)",             type: "noun" },
  { word: "晚上",  pinyin: "wǎnshang",  english: "evening / night",          type: "noun" },
  { word: "去年",  pinyin: "qùnián",    english: "last year",                type: "noun" },
  { word: "今年",  pinyin: "jīnnián",   english: "this year",                type: "noun" },
  { word: "明年",  pinyin: "míngnián",  english: "next year",                type: "noun" },
  { word: "周末",  pinyin: "zhōumò",    english: "weekend",                  type: "noun" },
  { word: "最近",  pinyin: "zuìjìn",    english: "recently / lately",        type: "noun" },
  { word: "以前",  pinyin: "yǐqián",    english: "before / in the past",     type: "noun" },
  { word: "以后",  pinyin: "yǐhòu",     english: "after / in the future",    type: "noun" },
  { word: "小时",  pinyin: "xiǎoshí",   english: "hour",                     type: "noun" },
  { word: "分钟",  pinyin: "fēnzhōng",  english: "minute",                   type: "noun" },

  // ── Objects / Things
  { word: "手机",  pinyin: "shǒujī",    english: "mobile phone",             type: "noun" },
  { word: "照片",  pinyin: "zhàopiàn",  english: "photo / photograph",       type: "noun" },
  { word: "礼物",  pinyin: "lǐwù",      english: "gift / present",           type: "noun" },
  { word: "书包",  pinyin: "shūbāo",    english: "school bag / backpack",    type: "noun" },
  { word: "帽子",  pinyin: "màozi",     english: "hat / cap",                type: "noun" },
  { word: "皮鞋",  pinyin: "píxié",     english: "leather shoes",            type: "noun" },
  { word: "手表",  pinyin: "shǒubiǎo",  english: "watch (wrist watch)",      type: "noun" },
  { word: "报纸",  pinyin: "bàozhǐ",    english: "newspaper",                type: "noun" },
  { word: "票",    pinyin: "piào",      english: "ticket",                   type: "noun" },

  // ── Food & Drink
  { word: "咖啡",  pinyin: "kāfēi",     english: "coffee",                   type: "noun" },
  { word: "牛奶",  pinyin: "niúnǎi",    english: "milk",                     type: "noun" },
  { word: "啤酒",  pinyin: "píjiǔ",     english: "beer",                     type: "noun" },
  { word: "菜",    pinyin: "cài",       english: "dish / vegetable / food",  type: "noun" },
  { word: "面条",  pinyin: "miàntiáo",  english: "noodles",                  type: "noun" },
  { word: "鸡蛋",  pinyin: "jīdàn",     english: "egg",                      type: "noun" },
  { word: "猪肉",  pinyin: "zhūròu",    english: "pork",                     type: "noun" },
  { word: "鱼",    pinyin: "yú",        english: "fish",                     type: "noun" },
  { word: "蛋糕",  pinyin: "dàngāo",    english: "cake",                     type: "noun" },

  // ── Body / Health
  { word: "身体",  pinyin: "shēntǐ",    english: "body / health",            type: "noun" },
  { word: "头",    pinyin: "tóu",       english: "head",                     type: "noun" },
  { word: "头发",  pinyin: "tóufa",     english: "hair",                     type: "noun" },
  { word: "眼睛",  pinyin: "yǎnjing",   english: "eyes",                     type: "noun" },
  { word: "耳朵",  pinyin: "ěrduō",     english: "ears",                     type: "noun" },

  // ── Transport
  { word: "飞机",  pinyin: "fēijī",     english: "airplane",                 type: "noun" },
  { word: "火车",  pinyin: "huǒchē",    english: "train",                    type: "noun" },
  { word: "公共汽车", pinyin: "gōnggòng qìchē", english: "bus",             type: "noun" },
  { word: "自行车", pinyin: "zìxíngchē", english: "bicycle",                type: "noun" },
  { word: "公里",  pinyin: "gōnglǐ",    english: "kilometer",               type: "noun" },

  // ── School / Work
  { word: "课",    pinyin: "kè",        english: "class / lesson",           type: "noun" },
  { word: "考试",  pinyin: "kǎoshì",    english: "exam / test",              type: "noun" },
  { word: "作业",  pinyin: "zuòyè",     english: "homework",                 type: "noun" },
  { word: "问题",  pinyin: "wèntí",     english: "question / problem",       type: "noun" },
  { word: "答案",  pinyin: "dá'àn",     english: "answer",                   type: "noun" },
  { word: "意思",  pinyin: "yìsi",      english: "meaning / interesting",    type: "noun" },
  { word: "兴趣",  pinyin: "xìngqù",    english: "interest / hobby",         type: "noun" },

  // ── Verbs
  { word: "需要",  pinyin: "xūyào",     english: "to need",                  type: "verb" },
  { word: "可以",  pinyin: "kěyǐ",      english: "can / may",                type: "verb" },
  { word: "告诉",  pinyin: "gàosù",     english: "to tell",                  type: "verb" },
  { word: "觉得",  pinyin: "juéde",     english: "to feel / to think",       type: "verb" },
  { word: "明白",  pinyin: "míngbái",   english: "to understand",            type: "verb" },
  { word: "知道",  pinyin: "zhīdào",    english: "to know",                  type: "verb" },
  { word: "帮",    pinyin: "bāng",      english: "to help",                  type: "verb" },
  { word: "给",    pinyin: "gěi",       english: "to give / for",            type: "verb" },
  { word: "送",    pinyin: "sòng",      english: "to give (as a gift) / send", type: "verb" },
  { word: "用",    pinyin: "yòng",      english: "to use",                   type: "verb" },
  { word: "花",    pinyin: "huā",       english: "to spend (money/time)",    type: "verb" },
  { word: "换",    pinyin: "huàn",      english: "to exchange / change",     type: "verb" },
  { word: "带",    pinyin: "dài",       english: "to bring / to wear (accessories)", type: "verb" },
  { word: "找",    pinyin: "zhǎo",      english: "to look for / to find",    type: "verb" },
  { word: "开",    pinyin: "kāi",       english: "to open / to drive",       type: "verb" },
  { word: "开始",  pinyin: "kāishǐ",    english: "to start / to begin",      type: "verb" },
  { word: "结束",  pinyin: "jiéshù",    english: "to end / to finish",       type: "verb" },
  { word: "准备",  pinyin: "zhǔnbèi",   english: "to prepare",               type: "verb" },
  { word: "教",    pinyin: "jiāo",      english: "to teach",                 type: "verb" },
  { word: "回答",  pinyin: "huídá",     english: "to answer",                type: "verb" },
  { word: "介绍",  pinyin: "jièshào",   english: "to introduce",             type: "verb" },
  { word: "旅游",  pinyin: "lǚyóu",     english: "to travel",                type: "verb" },
  { word: "骑",    pinyin: "qí",        english: "to ride (bike/horse)",     type: "verb" },
  { word: "游泳",  pinyin: "yóuyǒng",   english: "to swim",                  type: "verb" },
  { word: "跑步",  pinyin: "pǎobù",     english: "to jog / run",             type: "verb" },
  { word: "运动",  pinyin: "yùndòng",   english: "to exercise / sport",      type: "verb" },
  { word: "打篮球", pinyin: "dǎ lánqiú", english: "to play basketball",      type: "verb" },
  { word: "休息",  pinyin: "xiūxi",     english: "to rest",                  type: "verb" },
  { word: "生病",  pinyin: "shēngbìng", english: "to get sick",              type: "verb" },
  { word: "洗",    pinyin: "xǐ",        english: "to wash",                  type: "verb" },
  { word: "穿",    pinyin: "chuān",     english: "to wear (clothes/shoes)",  type: "verb" },
  { word: "起床",  pinyin: "qǐchuáng",  english: "to get up (from bed)",     type: "verb" },
  { word: "上班",  pinyin: "shàngbān",  english: "to go to work",            type: "verb" },
  { word: "下班",  pinyin: "xiàbān",    english: "to get off work",          type: "verb" },
  { word: "玩",    pinyin: "wán",       english: "to play / to have fun",    type: "verb" },
  { word: "出去",  pinyin: "chūqù",     english: "to go out",                type: "verb" },
  { word: "站",    pinyin: "zhàn",      english: "to stand",                 type: "verb" },
  { word: "等",    pinyin: "děng",      english: "to wait",                  type: "verb" },
  { word: "问",    pinyin: "wèn",       english: "to ask",                   type: "verb" },
  { word: "笑",    pinyin: "xiào",      english: "to laugh / to smile",      type: "verb" },
  { word: "哭",    pinyin: "kū",        english: "to cry",                   type: "verb" },

  // ── Adjectives
  { word: "忙",    pinyin: "máng",      english: "busy",                     type: "adj" },
  { word: "累",    pinyin: "lèi",       english: "tired",                    type: "adj" },
  { word: "快",    pinyin: "kuài",      english: "fast",                     type: "adj" },
  { word: "慢",    pinyin: "màn",       english: "slow",                     type: "adj" },
  { word: "早",    pinyin: "zǎo",       english: "early",                    type: "adj" },
  { word: "晚",    pinyin: "wǎn",       english: "late",                     type: "adj" },
  { word: "近",    pinyin: "jìn",       english: "close / near",             type: "adj" },
  { word: "远",    pinyin: "yuǎn",      english: "far",                      type: "adj" },
  { word: "贵",    pinyin: "guì",       english: "expensive",                type: "adj" },
  { word: "便宜",  pinyin: "piányí",    english: "cheap / inexpensive",      type: "adj" },
  { word: "甜",    pinyin: "tián",      english: "sweet",                    type: "adj" },
  { word: "新",    pinyin: "xīn",       english: "new",                      type: "adj" },
  { word: "旧",    pinyin: "jiù",       english: "old / used",               type: "adj" },
  { word: "对",    pinyin: "duì",       english: "correct / right",          type: "adj" },
  { word: "错",    pinyin: "cuò",       english: "wrong / incorrect",        type: "adj" },
  { word: "难",    pinyin: "nán",       english: "difficult",                type: "adj" },
  { word: "容易",  pinyin: "róngyì",    english: "easy",                     type: "adj" },
  { word: "有名",  pinyin: "yǒumíng",   english: "famous",                   type: "adj" },
  { word: "有意思", pinyin: "yǒu yìsi", english: "interesting",              type: "adj" },
  { word: "可爱",  pinyin: "kě'ài",     english: "cute / adorable",          type: "adj" },
  { word: "聪明",  pinyin: "cōngmíng",  english: "smart / clever",           type: "adj" },
  { word: "舒服",  pinyin: "shūfu",     english: "comfortable / well",       type: "adj" },
  { word: "饿",    pinyin: "è",         english: "hungry",                   type: "adj" },
  { word: "渴",    pinyin: "kě",        english: "thirsty",                  type: "adj" },
  { word: "黑",    pinyin: "hēi",       english: "black / dark",             type: "adj" },
  { word: "白",    pinyin: "bái",       english: "white",                    type: "adj" },
  { word: "红",    pinyin: "hóng",      english: "red",                      type: "adj" },
  { word: "长",    pinyin: "cháng",     english: "long",                     type: "adj" },

  // ── Adverbs
  { word: "已经",  pinyin: "yǐjīng",    english: "already",                  type: "adv" },
  { word: "最",    pinyin: "zuì",       english: "most / -est",              type: "adv" },
  { word: "非常",  pinyin: "fēicháng",  english: "extremely / very",         type: "adv" },
  { word: "总是",  pinyin: "zǒngshì",   english: "always",                   type: "adv" },
  { word: "从来",  pinyin: "cónglái",   english: "never (with 没)",          type: "adv" },
  { word: "突然",  pinyin: "tūrán",     english: "suddenly",                 type: "adv" },
  { word: "认真",  pinyin: "rènzhēn",   english: "seriously / diligently",   type: "adv" },
  { word: "一边",  pinyin: "yībiān",    english: "at the same time / side",  type: "adv" },
  { word: "越来越", pinyin: "yuèláiyuè", english: "more and more",           type: "adv" },

  // ── Conjunctions / Prepositions
  { word: "虽然",  pinyin: "suīrán",    english: "although / even though",   type: "conj" },
  { word: "如果",  pinyin: "rúguǒ",     english: "if",                       type: "conj" },
  { word: "然后",  pinyin: "ránhòu",    english: "then / after that",        type: "conj" },
  { word: "不然",  pinyin: "bùrán",     english: "otherwise",                type: "conj" },
  { word: "比",    pinyin: "bǐ",        english: "than (comparison)",        type: "prep" },
  { word: "从",    pinyin: "cóng",      english: "from",                     type: "prep" },
  { word: "离",    pinyin: "lí",        english: "away from / distance",     type: "prep" },
  { word: "往",    pinyin: "wǎng",      english: "towards / in the direction of", type: "prep" },
  { word: "为什么", pinyin: "wèishénme", english: "why",                     type: "pron" },
  { word: "怎么",  pinyin: "zěnme",     english: "how / why",                type: "pron" },
  { word: "怎么样", pinyin: "zěnmeyàng", english: "how is it? what's it like?", type: "pron" },
];
